# Macro file for leap_sims
#
/leap_sims/phys/addPhysics emlivermore_polar

# Initialize kernel
/run/initialize

/polarization/manager/verbose 1
/polarization/volume/set magnetLV 0. 0. 1.
/polarization/volume/list
#
# Default kinematics:
# electron 60 MeV in direction (0.,0.,1.)
#/gun/particle gamma
/gun/number 100000
/gun/energy 60 MeV
/gun/polarization 0. 0. 1.

#/leapsim/det/setTargThick 1 mm 
/leapsim/det/setAbsThick 10 cm
#/leapsim/det/update


#/tracking/verbose 0
#/run/printProgress 1
/run/beamOn 1

